/* Orion's abilities in the 3D network. `tools` — which skills light up the bubble. */
export const NODES = [
  { id: 'ear', label: 'Hearing', about: 'Hears you when you say “Orion” or press F2.' },
  { id: 'voice', label: 'Voice', about: 'The voice it answers you with.' },
  { id: 'clock', label: 'Clock', tools: ['get_current_time', 'days_until_date'],
    about: 'Time, date, day of the week and the time around the world.' },
  { id: 'weather', label: 'Weather', tools: ['get_weather'], about: 'The weather outside in any city.' },
  { id: 'calc', label: 'Maths', tools: ['calculate', 'convert_units', 'convert_currency'],
    about: 'Exact calculations, units and currencies at today’s rate.' },
  { id: 'apps', label: 'Apps', tools: ['open_program', 'open_website', 'list_games'],
    about: 'Opens programs, games (Steam, Riot, Epic) and websites.' },
  { id: 'markets', label: 'Markets', tools: ['market_price', 'analyze_market', 'analyze_price_file', 'market_overview', 'crypto_market'],
    about: 'Stocks, crypto, currencies, gold — prices and technical analysis with a chart. Not investment advice.' },
  { id: 'claude', label: 'Claude', tools: ['ask_claude', 'send_to_claude_app'],
    about: 'Asks Claude about complex tasks or writes to it in the app.' },
  { id: 'tools', label: 'Tools', about: 'Passwords, dice and coins, QR codes, encoding, statistics, percentages.' },
  { id: 'net', label: 'Network', about: 'Internet speed, IP, ping, is a site up, ports, Docker.' },
  { id: 'places', label: 'Places', about: 'Countries, distances, routes and “what is nearby” in Google Maps.' },
  { id: 'web', label: 'Internet', tools: ['search_web', 'read_webpage', 'wikipedia'],
    about: 'Searches the internet, reads pages and checks facts on Wikipedia.' },
  { id: 'media', label: 'Media', tools: ['play_on_youtube', 'media_control', 'set_volume', 'change_volume', 'mute_sound'],
    about: 'Plays songs on YouTube, pause and next song, volume. Cuts reels from videos.' },
  { id: 'system', label: 'System', tools: ['system_status', 'close_program', 'power_action'],
    about: 'Computer status, closing programs, locking and shutting down.' },
  { id: 'screen', label: 'Vision', tools: ['look_at_screen', 'look_at_image', 'take_screenshot', 'read_clipboard', 'copy_to_clipboard'],
    about: 'Looks at the screen and photos, reads copied text. Images stay on the computer.' },
  { id: 'files', label: 'Files', tools: ['open_folder', 'find_files', 'open_file'],
    about: 'Finds and opens files and folders.' },
  { id: 'mail', label: 'Mail', tools: ['check_email', 'read_email', 'send_email', 'reply_email'],
    about: 'Gmail: reads, replies and sends — only after you press “Send”.' },
  { id: 'calendar', label: 'Calendar', tools: ['calendar_events', 'calendar_add_event', 'calendar_delete_event'],
    about: 'Google Calendar: meetings and events.' },
  { id: 'tasks', label: 'Tasks', tools: ['tasks_list', 'tasks_add', 'tasks_complete'],
    about: 'Google Tasks: what you have to do.' },
  { id: 'reminders', label: 'Reminders', tools: ['set_reminder', 'set_timer', 'list_reminders', 'cancel_reminder'],
    about: 'Reminders and timers — announced out loud.' },
  { id: 'memory', label: 'Memory', tools: ['remember', 'learn_lesson', 'list_lessons', 'forget_lesson'],
    about: 'Remembers facts about you and lessons from its mistakes.' },
  { id: 'evolve', label: 'Evolution', tools: ['create_skill', 'improve_skill', 'undo_skill_change', 'recent_errors'],
    about: 'Writes and fixes its own skills — after your approval.' },
];

// Skill groups (the modules in skills/) -> the bubble that lights up for them.
export const MODULE_NODES = {
  'skills.util_skills': 'tools', 'skills.finance_skills': 'calc', 'skills.notes_skills': 'memory',
  'skills.time_skills': 'clock', 'skills.weather_skills': 'weather', 'skills.net_skills': 'net',
  'skills.file_skills': 'files', 'skills.windows_skills': 'system', 'skills.places_skills': 'places',
  'skills.media_skills': 'media', 'skills.trading_skills': 'markets', 'skills.language_skills': 'web',
  'skills.assistant_skills': 'memory', 'skills.reels_skills': 'media',
};

const shortUrl = (url = '') => url.replace(/^https?:\/\/(www\.)?/, '').split(/[/?#]/)[0];
const quoted = (s = '') => `„${String(s).slice(0, 34)}${String(s).length > 34 ? '…' : ''}“`;

// What the skill is doing — the caption of the task bubble.
export const TASK_TEXT = {
  get_current_time: (a) => (a.city ? `time in ${a.city}` : 'the exact time'),
  days_until_date: (a) => `days until ${a.date_str}`,
  get_weather: (a) => (a.city ? `weather in ${a.city}` : 'the weather outside'),
  calculate: (a) => a.expression,
  make_youtube_reels: (a) => `reels · ${a.count || 3} × ${a.seconds || 45} s`,
  analyze_youtube_video: () => 'most-watched moments',
  find_free_videos: (a) => `free videos: ${a.topic || ''}`,
  auto_reels: (a) => (a.topic ? `choosing a clip · ${a.topic}` : 'choosing a clip for reels'),
  open_program: (a) => `opening ${a.name}`,
  open_website: (a) => `opening ${shortUrl(a.url)}`,
  search_web: (a) => `searching ${quoted(a.query)}`,
  read_webpage: (a) => `reading ${shortUrl(a.url)}`,
  check_email: (a) => (a.search ? `emails: ${a.search}` : 'new emails'),
  read_email: (a) => `reading email ${a.number || 1}`,
  send_email: (a) => `email to ${a.to}`,
  reply_email: (a) => `reply to email ${a.number}`,
  calendar_events: (a) => `calendar · ${a.day || 'today'}`,
  calendar_add_event: (a) => `adding ${quoted(a.title)}`,
  calendar_delete_event: (a) => `deleting ${quoted(a.title)}`,
  tasks_list: () => 'the task list',
  tasks_add: (a) => `task ${quoted(a.title)}`,
  tasks_complete: (a) => `done: ${a.title}`,
  set_reminder: (a) => `reminder ${a.when_text}`,
  set_timer: (a) => `timer ${a.duration}`,
  list_reminders: () => 'pending reminders',
  cancel_reminder: (a) => `cancelling ${a.what || 'all'}`,
  remember: () => 'remembering',
  learn_lesson: () => 'learning a lesson',
  list_lessons: () => 'my lessons',
  forget_lesson: () => 'forgetting a lesson',
  create_skill: () => 'writing a new skill',
  improve_skill: (a) => `fixing ${a.tool_name || 'a skill'}`,
  undo_skill_change: () => 'undoing a change',
  recent_errors: () => 'recent errors',
  wikipedia: (a) => `Wikipedia: ${a.topic}`,
  convert_units: (a) => `${a.value} ${a.from_unit} → ${a.to_unit}`,
  convert_currency: (a) => `${a.amount} ${a.from_currency} → ${a.to_currency}`,
  play_on_youtube: (a) => `playing ${quoted(a.query)}`,
  media_control: (a) => ({ play: 'play', pause: 'pause', next: 'next', previous: 'previous', stop: 'stop' }[a.action] || a.action),
  set_volume: (a) => `volume ${a.level}%`,
  change_volume: (a) => `volume ${a.amount > 0 ? '+' : ''}${a.amount}%`,
  mute_sound: (a) => (a.mute === false ? 'sound back on' : 'muting'),
  system_status: () => 'computer status',
  close_program: (a) => `closing ${a.name}`,
  power_action: (a) => ({ lock: 'locking', sleep: 'sleep', shutdown: 'shutdown', restart: 'restart', cancel: 'cancelling shutdown' }[a.action] || a.action),
  look_at_screen: () => 'looking at the screen',
  look_at_image: () => 'looking at the image',
  take_screenshot: () => 'screenshot',
  read_clipboard: () => 'reading the clipboard',
  copy_to_clipboard: () => 'copying',
  open_folder: (a) => `folder ${a.name}`,
  find_files: (a) => `finding file ${quoted(a.query)}`,
  open_file: (a) => `opening file ${a.number || 1}`,
  list_games: () => 'my games',
  market_price: (a) => `price: ${a.asset}`,
  analyze_market: (a) => `analysis ${a.asset} · ${a.timeframe || '1d'}`,
  analyze_price_file: (a) => `analysing ${a.file_name}`,
  market_overview: () => 'markets today',
  crypto_market: () => 'the crypto market',
  ask_claude: (a) => `asking Claude: ${quoted(a.question)}`,
  send_to_claude_app: () => 'writing to Claude',
};
