const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const has = (name, ...args) => window.calls.some((c) => c[0] === name && JSON.stringify(c.slice(1)) === JSON.stringify(args));
async function run() {
  const out = [];
  const check = (label, ok) => out.push(`${ok ? 'PASS' : 'FAIL'} ${label}`);
  window.dispatchEvent(new Event('pywebviewready'));
  await wait(200);
  check('start() called and switches set', has('start') && document.querySelectorAll('.switch input')[0].checked === true);
  hud.showConfirm({ title: 'Email to send', summary: 'To: a@b.c', body: 'Hi', accept: 'Send' });
  await wait(100);
  check('confirm focuses Reject', document.activeElement?.textContent === 'Reject');
  document.querySelector('.btn-reject').click();
  await wait(100);
  check('Reject -> resolve_approval(false), dialog gone', has('resolve_approval', false) && !document.querySelector('.approval'));
  hud.showApproval({ kind: 'create', title: 't', reason: 'r', code: 'print(1)', diff: '', warnings: [], tools: ['x'], attempts: 1 });
  await wait(100);
  document.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
  await wait(100);
  check('Escape rejects approval', window.calls.filter((c) => c[0] === 'resolve_approval').length === 2 && !document.querySelector('.approval'));
  const input = document.getElementById('command-input');
  input.value = '  здравей  ';
  input.form.requestSubmit();
  await wait(100);
  check('Send -> send_text("здравей"), box cleared', has('send_text', 'здравей') && input.value === '');
  document.querySelectorAll('.switch input')[1].click();
  await wait(100);
  check('Voice off -> set_muted(true)', has('set_muted', true));
  hud.playAudio('AAAA');
  check('audio with voice off -> speech_finished', has('speech_finished'));
  document.dispatchEvent(new KeyboardEvent('keydown', { key: 'F2', bubbles: true }));
  check('F2 -> listen()', has('listen'));
  hud.setSwitch('test', true);
  await wait(50);
  check('Python setSwitch(test) checks the box', document.querySelectorAll('.switch input')[2].checked);
  hud.setTest({ active: true, text: 'round 1' });
  await wait(50);
  check('test chip shown', document.querySelector('.tele-chip')?.textContent === 'test · round 1');
  hud.setSwitch('test', false);
  await wait(50);
  check('test off hides chip', !document.querySelector('.tele-chip'));
  hud.addLog('claude', 'a **b** <img src=x onerror=alert(1)> `c`');
  await wait(50);
  const last = [...document.querySelectorAll('.entry')].at(-1);
  check('claude markdown safe (bold, code, no img)', last.querySelector('strong')?.textContent === 'b' && last.querySelector('code') && !last.querySelector('img'));
  hud.bootLine('a', 'A', 'run', 'x'); hud.bootLine('a', 'A', 'ok', 'y');
  await wait(50);
  check('boot line updated in place', document.querySelectorAll('.boot li').length === 1 && document.querySelector('.boot li').className === 'is-ok');
  hud.setState('listening');
  await wait(50);
  check('state listening on .app + mic pressed', document.querySelector('.app').dataset.state === 'listening' && document.querySelector('.mic').getAttribute('aria-pressed') === 'true');
  document.querySelector('.winctl button:nth-child(2)').click();
  check('maximize -> window_maximize(true)', has('window_maximize', true));

  const n = 40, close = Array.from({ length: n }, (_, i) => 50 + i);
  hud.showChart({ name: 'Gold', currency: 'USD', timeframe: '4h', change: -1.25, close, sma20: close.map(() => null), sma50: close.map(() => null),
    time: close.map((_, i) => `t${i}`), support: 45, resistance: 95 });
  await wait(150);
  const cv = document.querySelector('.entry--chart canvas');
  check('chart canvas drawn (180 px high, pixels set)', cv && cv.clientHeight === 180 && cv.width > 0);
  check('chart meta text', document.querySelector('.chart-meta')?.textContent === '4-hour candles · -1.3%');
  const r = cv.getBoundingClientRect();
  cv.dispatchEvent(new PointerEvent('pointermove', { clientX: r.left + r.width / 2, clientY: r.top + 50, bubbles: true }));
  await wait(100);
  const tipRows = document.querySelectorAll('.chart-tip > span');
  check('chart hover tooltip (4 rows, price shown)', tipRows.length === 4 && /Price \d/.test(tipRows[1].textContent));
  cv.dispatchEvent(new PointerEvent('pointerout', { bubbles: true, relatedTarget: document.body }));  // a real mouse leaving
  await wait(100);
  check('tooltip hides on leave', !document.querySelector('.chart-tip'));
  hud.say('Тест на субтитрите.');
  await wait(400);
  check('say -> journal + subtitle', document.querySelector('.subtitle')?.textContent === 'Тест на субтитрите.' && [...document.querySelectorAll('.entry--orion p')].at(-1)?.textContent === 'Тест на субтитрите.');
  hud.heard('какво е времето');
  await wait(400);
  check('heard -> amber user subtitle', document.querySelector('.subtitle.is-user')?.textContent === 'какво е времето');
  let threw = null;
  try {
    hud.toolStart('get_weather', { city: 'Sofia' }, 'skills.weather_skills', '');
    hud.toolDone('get_weather', 'Sofia: 18°C', true);
    hud.toolStart('test:x', {}, '', 'label'); hud.toolDone('test:x', 'bad', false);
    hud.thought('Мисля...'); hud.setReminders([{ kind: 'reminder', due: new Date().toISOString() }]);
    hud.setState('no-such-state');
  } catch (e) { threw = e; }
  await wait(200);
  check('network events do not fail, unknown state ignored', !threw && document.querySelector('.app').dataset.state === 'listening');
  hud.setReels({ active: true, text: 'cutting reel 1/3' });
  await wait(50);
  check('reels chip', document.querySelector('.tele-chip--reels')?.textContent === 'reels · cutting reel 1/3');
  hud.setTelemetry({ model: 'm', skills: 1, docs: 2, lessons: 1 });
  await wait(50);
  check('telemetry text', document.querySelector('.tele-model')?.textContent === 'm · 1 skill · 2 docs · 1 lesson');
  hud.bootLine('llm', 'Language model', 'fail', 'Ollama is not running');
  hud.bootDone(false);
  await wait(50);
  check('boot failure -> offline, error stays visible', document.querySelector('.app').dataset.state === 'offline' && document.querySelector('.boot .is-fail'));
  check('no errors reported to Python', !window.calls.some((c) => c[0] === 'report_error'));

  hud.addLog('reels', '1. „Space“ — Ch · 4:42 · https://www.youtube.com/watch?v=yn17NXaOCGc, also javascript:alert(1) here');
  await wait(100);
  const link = [...document.querySelectorAll('.entry--reels a')].at(-1);
  check('URL in the journal is a link (comma left out)', link && link.textContent === 'https://www.youtube.com/watch?v=yn17NXaOCGc');
  link?.click();
  await wait(50);
  check('click -> open_link(url), page does not navigate', has('open_link', 'https://www.youtube.com/watch?v=yn17NXaOCGc') && location.href.includes('interact.html'));
  check('javascript: text is not a link', ![...document.querySelectorAll('.entry a')].some((a) => a.textContent.startsWith('javascript')));
  check('the eyes are drawn in the centre', Boolean(document.querySelector('.eyes canvas')));
  const eyesBox = document.querySelector('.eyes').getBoundingClientRect();
  const stageBox = document.querySelector('.stage').getBoundingClientRect();
  check('the eyes are inside the stage', eyesBox.left >= stageBox.left - 1 && eyesBox.right <= stageBox.right + 1);
  const ev = (o) => ({ trace: 500, detail: null, key: o.key || o.phase, t: 0, ms: null, ok: null, ...o });
  hud.live(ev({ phase: 'heard', state: 'end', label: 'Ще вали ли утре?', detail: { source: 'voice', google: 'ще вали ли утре', whisper: 'Ще вали ли утре?' }, ms: 140 }));
  hud.live(ev({ phase: 'understood', state: 'start', label: 'choosing' }));
  hud.live(ev({ phase: 'understood', state: 'end', label: 'quick command', detail: { command: 'will_it_rain' }, ms: 2, ok: true }));
  hud.live(ev({ phase: 'skill', state: 'start', label: 'will_it_rain', key: 'will_it_rain' }));
  await wait(100);
  check('pipeline shows the running skill', document.querySelector('.pipe-step[data-phase="skill"]')?.className.includes('is-run'));
  document.querySelector('.pipe-step[data-phase="heard"]').click();
  await wait(100);
  check('heard details show both transcripts', document.querySelector('.step-details')?.textContent.includes('ще вали ли утре'));
  hud.live(ev({ phase: 'skill', state: 'end', label: 'will_it_rain', key: 'will_it_rain', ms: 380, ok: true }));
  hud.live(ev({ phase: 'done', state: 'end', label: 'done', ok: true, ms: 900 }));
  hud.setGauges({ gpu: 21, vramUsed: 7000, vramTotal: 10240, cpu: 9, ram: 51 });
  await wait(100);
  check('gauges in the top bar', document.querySelector('.gauges')?.textContent.includes('GPU 21%'));
  check('the last answer time', document.querySelector('.gauges')?.textContent.includes('last 900 ms'));
  hud.live(ev({ trace: 999, phase: 'skill', state: 'end', label: 'ghost', key: 'ghost' }));
  check('events of unknown traces are ignored', !document.body.textContent.includes('ghost'));
  const pre = document.createElement('pre'); pre.id = 'result'; pre.textContent = out.join('\n'); document.body.append(pre);
}
window.addEventListener('load', () => setTimeout(run, 100));
